[package]
name = "chapter_01_thread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affinity = "0.1.2"
num_cpus = "1.16.0"
num_threads = "0.1.6"
thread-amount = "0.1.3"
